### ISSUE TITLE
What's the best way to check the demo?

### ISSUE THREAD

**Issue by vjustov** [iotacss/react-iotacss#4]
I cloned the repo and cd'd onto the demo folder, and opened the index file. Nothing happens.
I imagine that this is due to the fact that its referencing a bundle.js but the js file in the folder is named entry.js... thing is, entry.js is using ES6 syntax, arent we missing a package.json or webpack.config in that folder? Maybe also a readme would be nice.

Thanks you for the good work.

**Comment by harby** [comment]
Good idea. Just added documentation for the demo.
